import argparse
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from beanie import init_beanie
from motor.motor_asyncio import AsyncIOMotorClient

CAREERS = [
    {
        "nombre": "Ingeniería de Sistemas",
        "slug": "ingenieria-de-sistemas",
        "descripcion": "Diseño y desarrollo de software, sistemas de información y arquitecturas tecnológicas.",
        "categoria": "tech",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 4500000,
        "salarioEntrada": 3200000,
        "salarioMedio": 6800000,
        "salarioMediana": 5500000,
        "empleabilidad": 88.0,
        "tasaEmpleabilidad12m": 85.0,
        "demandaPorRegion": {"bogotá": 92, "medellín": 88, "cali": 75, "barranquilla": 70},
        "universidades": ["Universidad Nacional", "Universidad de los Andes", "EAFIT", "Javeriana"],
        "habilidadesRequeridas": ["programación", "algoritmos", "bases de datos", "matemáticas"],
        "tags": ["tecnología", "software", "programación", "sistemas"],
        "proyeccion2030": "Alta demanda por transformación digital empresarial y gobierno digital.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Medicina",
        "slug": "medicina",
        "descripcion": "Diagnóstico, tratamiento y prevención de enfermedades en seres humanos.",
        "categoria": "salud",
        "tipo": "universitaria",
        "duracionSemestres": 12,
        "costoSemestre": 8500000,
        "salarioEntrada": 4500000,
        "salarioMedio": 12000000,
        "salarioMediana": 10000000,
        "empleabilidad": 94.0,
        "tasaEmpleabilidad12m": 90.0,
        "demandaPorRegion": {"bogotá": 95, "medellín": 92, "cali": 88, "barranquilla": 82, "bucaramanga": 78},
        "universidades": ["Universidad Nacional", "Universidad de Antioquia", "Javeriana", "Universidad del Rosario"],
        "habilidadesRequeridas": ["ciencias naturales", "química", "biología", "empatía"],
        "tags": ["salud", "medicina", "ciencias", "vocación"],
        "proyeccion2030": "Déficit de médicos en zonas rurales; alta demanda en telemedicina.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Derecho",
        "slug": "derecho",
        "descripcion": "Estudio del ordenamiento jurídico, defensa legal y administración de justicia.",
        "categoria": "justicia",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 5200000,
        "salarioEntrada": 2800000,
        "salarioMedio": 7500000,
        "salarioMediana": 5800000,
        "empleabilidad": 78.0,
        "tasaEmpleabilidad12m": 72.0,
        "demandaPorRegion": {"bogotá": 90, "medellín": 80, "cali": 75, "barranquilla": 70},
        "universidades": ["Universidad Externado", "Universidad Nacional", "Javeriana", "Universidad del Rosario"],
        "habilidadesRequeridas": ["argumentación", "redacción", "análisis", "ética"],
        "tags": ["justicia", "derecho", "ley", "abogacía"],
        "proyeccion2030": "Crecimiento en derecho digital, protección de datos y litigios corporativos.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Administración de Empresas",
        "slug": "administracion-de-empresas",
        "descripcion": "Gestión estratégica, financiera y operativa de organizaciones empresariales.",
        "categoria": "negocios",
        "tipo": "universitaria",
        "duracionSemestres": 9,
        "costoSemestre": 4200000,
        "salarioEntrada": 2500000,
        "salarioMedio": 6200000,
        "salarioMediana": 5000000,
        "empleabilidad": 82.0,
        "tasaEmpleabilidad12m": 78.0,
        "demandaPorRegion": {"bogotá": 88, "medellín": 85, "cali": 80, "barranquilla": 78, "bucaramanga": 75},
        "universidades": ["Universidad de los Andes", "EAFIT", "Javeriana", "Universidad Nacional"],
        "habilidadesRequeridas": ["liderazgo", "finanzas", "estrategia", "comunicación"],
        "tags": ["negocios", "empresa", "gestión", "emprendimiento"],
        "proyeccion2030": "Alta demanda en startups, transformación digital y comercio internacional.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Psicología",
        "slug": "psicologia",
        "descripcion": "Estudio del comportamiento humano y procesos mentales para el bienestar individual y social.",
        "categoria": "social",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 3800000,
        "salarioEntrada": 2200000,
        "salarioMedio": 4800000,
        "salarioMediana": 4200000,
        "empleabilidad": 75.0,
        "tasaEmpleabilidad12m": 68.0,
        "demandaPorRegion": {"bogotá": 85, "medellín": 80, "cali": 75, "barranquilla": 70},
        "universidades": ["Universidad Nacional", "Javeriana", "Universidad de los Andes", "Universidad del Norte"],
        "habilidadesRequeridas": ["empatía", "comunicación", "análisis", "investigación"],
        "tags": ["psicología", "salud mental", "bienestar", "ciencias sociales"],
        "proyeccion2030": "Crecimiento en salud mental corporativa y telesalud psicológica.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Enfermería",
        "slug": "enfermeria",
        "descripcion": "Cuidado integral de pacientes, promoción de salud y prevención de enfermedades.",
        "categoria": "salud",
        "tipo": "universitaria",
        "duracionSemestres": 8,
        "costoSemestre": 3500000,
        "salarioEntrada": 2800000,
        "salarioMedio": 5500000,
        "salarioMediana": 4800000,
        "empleabilidad": 91.0,
        "tasaEmpleabilidad12m": 89.0,
        "demandaPorRegion": {"bogotá": 90, "medellín": 88, "cali": 85, "barranquilla": 82, "bucaramanga": 80},
        "universidades": ["Universidad Nacional", "Universidad de Antioquia", "Universidad del Valle", "Universidad del Norte"],
        "habilidadesRequeridas": ["cuidado", "ciencias de la salud", "empatía", "trabajo en equipo"],
        "tags": ["salud", "enfermería", "cuidado", "hospital"],
        "proyeccion2030": "Alta demanda por envejecimiento poblacional y expansión de servicios de salud rurales.",
        "acreditadaAltaCalidad": False,
        "verificado": True,
    },
    {
        "nombre": "Contaduría Pública",
        "slug": "contaduria-publica",
        "descripcion": "Control financiero, auditoría, tributación y asesoría contable para organizaciones.",
        "categoria": "negocios",
        "tipo": "universitaria",
        "duracionSemestres": 9,
        "costoSemestre": 3200000,
        "salarioEntrada": 2200000,
        "salarioMedio": 5200000,
        "salarioMediana": 4500000,
        "empleabilidad": 80.0,
        "tasaEmpleabilidad12m": 76.0,
        "demandaPorRegion": {"bogotá": 85, "medellín": 82, "cali": 78, "barranquilla": 75, "bucaramanga": 72},
        "universidades": ["Universidad Nacional", "Universidad Externado", "Universidad Jorge Tadeo Lozano", "UNIMINUTO"],
        "habilidadesRequeridas": ["matemáticas", "análisis", "ética", "atención al detalle"],
        "tags": ["contabilidad", "finanzas", "auditoría", "tributos"],
        "proyeccion2030": "Demanda estable; crecimiento en automatización contable y fintech.",
        "acreditadaAltaCalidad": False,
        "verificado": True,
    },
    {
        "nombre": "Arquitectura",
        "slug": "arquitectura",
        "descripcion": "Diseño y planificación de espacios, edificaciones y entornos urbanos sostenibles.",
        "categoria": "arte",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 4800000,
        "salarioEntrada": 2500000,
        "salarioMedio": 6000000,
        "salarioMediana": 5200000,
        "empleabilidad": 72.0,
        "tasaEmpleabilidad12m": 65.0,
        "demandaPorRegion": {"bogotá": 88, "medellín": 85, "cali": 75, "barranquilla": 72},
        "universidades": ["Universidad Nacional", "Universidad de los Andes", "Universidad Javeriana", "Universidad del Valle"],
        "habilidadesRequeridas": ["diseño", "creatividad", "matemáticas", "dibujo técnico"],
        "tags": ["arquitectura", "diseño", "urbanismo", "construcción"],
        "proyeccion2030": "Crecimiento en arquitectura sostenible y ciudades inteligentes.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Diseño Gráfico",
        "slug": "diseno-grafico",
        "descripcion": "Comunicación visual, identidad de marca y diseño digital para medios impresos y digitales.",
        "categoria": "arte",
        "tipo": "universitaria",
        "duracionSemestres": 8,
        "costoSemestre": 3800000,
        "salarioEntrada": 1800000,
        "salarioMedio": 4200000,
        "salarioMediana": 3500000,
        "empleabilidad": 70.0,
        "tasaEmpleabilidad12m": 64.0,
        "demandaPorRegion": {"bogotá": 90, "medellín": 85, "cali": 75, "barranquilla": 68},
        "universidades": ["Universidad Jorge Tadeo Lozano", "Universidad de los Andes", "Universidad Nacional", "Bellas Artes"],
        "habilidadesRequeridas": ["creatividad", "software gráfico", "comunicación visual", "estética"],
        "tags": ["diseño", "arte", "creatividad", "multimedia"],
        "proyeccion2030": "Alta demanda en diseño UX/UI, motion graphics y branding digital.",
        "acreditadaAltaCalidad": False,
        "verificado": True,
    },
    {
        "nombre": "Ingeniería Industrial",
        "slug": "ingenieria-industrial",
        "descripcion": "Optimización de procesos productivos, logística, calidad y gestión de operaciones.",
        "categoria": "ingenieria",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 4300000,
        "salarioEntrada": 3000000,
        "salarioMedio": 6500000,
        "salarioMediana": 5500000,
        "empleabilidad": 85.0,
        "tasaEmpleabilidad12m": 82.0,
        "demandaPorRegion": {"bogotá": 88, "medellín": 90, "cali": 82, "barranquilla": 78, "bucaramanga": 75},
        "universidades": ["Universidad Nacional", "Universidad de los Andes", "EAFIT", "Universidad del Valle"],
        "habilidadesRequeridas": ["estadística", "procesos", "liderazgo", "matemáticas"],
        "tags": ["ingeniería", "industria", "procesos", "manufactura"],
        "proyeccion2030": "Crecimiento en industria 4.0, automatización y cadenas de suministro.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Comunicación Social",
        "slug": "comunicacion-social",
        "descripcion": "Producción periodística, medios de comunicación, relaciones públicas y comunicación organizacional.",
        "categoria": "comunicacion",
        "tipo": "universitaria",
        "duracionSemestres": 9,
        "costoSemestre": 3600000,
        "salarioEntrada": 1900000,
        "salarioMedio": 4500000,
        "salarioMediana": 3800000,
        "empleabilidad": 68.0,
        "tasaEmpleabilidad12m": 62.0,
        "demandaPorRegion": {"bogotá": 92, "medellín": 80, "cali": 75, "barranquilla": 72},
        "universidades": ["Universidad Javeriana", "Universidad del Norte", "Universidad de Antioquia", "Universidad Nacional"],
        "habilidadesRequeridas": ["escritura", "oratoria", "investigación", "creatividad"],
        "tags": ["comunicación", "periodismo", "medios", "redes sociales"],
        "proyeccion2030": "Alta demanda en comunicación digital, podcasting y marketing de contenidos.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Ingeniería Civil",
        "slug": "ingenieria-civil",
        "descripcion": "Diseño, construcción y mantenimiento de infraestructura vial, hidráulica y estructural.",
        "categoria": "ingenieria",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 4100000,
        "salarioEntrada": 3200000,
        "salarioMedio": 7200000,
        "salarioMediana": 6000000,
        "empleabilidad": 83.0,
        "tasaEmpleabilidad12m": 80.0,
        "demandaPorRegion": {"bogotá": 85, "medellín": 82, "cali": 78, "barranquilla": 80, "bucaramanga": 76},
        "universidades": ["Universidad Nacional", "Universidad de los Andes", "Universidad del Valle", "EIA"],
        "habilidadesRequeridas": ["cálculo", "física", "diseño estructural", "gestión de proyectos"],
        "tags": ["ingeniería", "construcción", "infraestructura", "obras"],
        "proyeccion2030": "Alta demanda por plan de infraestructura vial y proyectos 5G.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Tecnología en Desarrollo de Software",
        "slug": "tecnologia-desarrollo-software",
        "descripcion": "Desarrollo de aplicaciones web y móviles, programación full-stack y fundamentos DevOps.",
        "categoria": "tech",
        "tipo": "tecnologica",
        "duracionSemestres": 6,
        "costoSemestre": 2800000,
        "salarioEntrada": 2500000,
        "salarioMedio": 5500000,
        "salarioMediana": 4800000,
        "empleabilidad": 90.0,
        "tasaEmpleabilidad12m": 88.0,
        "demandaPorRegion": {"bogotá": 90, "medellín": 88, "cali": 78, "barranquilla": 72},
        "universidades": ["SENA", "Politécnico Grancolombiano", "Universidad ECCI", "Uniminuto"],
        "habilidadesRequeridas": ["programación", "web", "bases de datos", "metodologías ágiles"],
        "tags": ["tecnología", "software", "desarrollo", "web", "programación"],
        "proyeccion2030": "Una de las carreras con mayor empleabilidad a 2030 por demanda de talento digital.",
        "acreditadaAltaCalidad": False,
        "verificado": True,
    },
    {
        "nombre": "Licenciatura en Educación Básica",
        "slug": "licenciatura-educacion-basica",
        "descripcion": "Formación docente para educación primaria y secundaria con énfasis en pedagogía activa.",
        "categoria": "educacion",
        "tipo": "universitaria",
        "duracionSemestres": 10,
        "costoSemestre": 2500000,
        "salarioEntrada": 2000000,
        "salarioMedio": 3800000,
        "salarioMediana": 3500000,
        "empleabilidad": 76.0,
        "tasaEmpleabilidad12m": 72.0,
        "demandaPorRegion": {"bogotá": 80, "medellín": 78, "cali": 75, "barranquilla": 70, "bucaramanga": 68},
        "universidades": ["Universidad Pedagógica Nacional", "Universidad de Antioquia", "Universidad del Valle", "UNIMINUTO"],
        "habilidadesRequeridas": ["pedagogía", "comunicación", "paciencia", "creatividad"],
        "tags": ["educación", "docencia", "pedagogía", "enseñanza"],
        "proyeccion2030": "Demanda sostenida por expansión de cobertura educativa y educación rural.",
        "acreditadaAltaCalidad": True,
        "verificado": True,
    },
    {
        "nombre": "Trabajo Social",
        "slug": "trabajo-social",
        "descripcion": "Intervención social, gestión comunitaria y políticas de bienestar para poblaciones vulnerables.",
        "categoria": "social",
        "tipo": "universitaria",
        "duracionSemestres": 9,
        "costoSemestre": 2800000,
        "salarioEntrada": 1900000,
        "salarioMedio": 3800000,
        "salarioMediana": 3200000,
        "empleabilidad": 70.0,
        "tasaEmpleabilidad12m": 65.0,
        "demandaPorRegion": {"bogotá": 82, "medellín": 78, "cali": 72, "barranquilla": 68},
        "universidades": ["Universidad Nacional", "Universidad de Antioquia", "Universidad del Valle", "Universidad Externado"],
        "habilidadesRequeridas": ["empatía", "gestión comunitaria", "investigación social", "comunicación"],
        "tags": ["social", "comunidad", "bienestar", "inclusión"],
        "proyeccion2030": "Crecimiento en programas de posconflicto, migración y envejecimiento activo.",
        "acreditadaAltaCalidad": False,
        "verificado": True,
    },
]


async def main(reset: bool) -> None:
    from dotenv import load_dotenv
    load_dotenv()

    from config import get_settings
    from app.models.carrera import Carrera

    settings = get_settings()
    client = AsyncIOMotorClient(settings.MONGODB_URI)
    await init_beanie(database=client.get_default_database(), document_models=[Carrera])

    if reset:
        await Carrera.delete_all()
        print("Existing careers deleted.")

    inserted = 0
    skipped = 0
    for career_data in CAREERS:
        existing = await Carrera.find_one({"slug": career_data["slug"]})
        if existing:
            skipped += 1
            continue
        await Carrera(**career_data).insert()
        inserted += 1

    print(f"Done: {inserted} inserted, {skipped} skipped.")
    client.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed EduRoad careers database.")
    parser.add_argument("--reset", action="store_true", help="Delete all careers before seeding.")
    args = parser.parse_args()
    asyncio.run(main(reset=args.reset))
